version: "3"
services:
  gateway-server:
    environment:
      CONFIG_PROFILE: dev
      CONFIG_LOGIN_PWD: 12345
    image: itmabo/gateway-server
    volumes:
      - /home/log:/home/log
    ports:
      - 8080:8080
#    networks:
#      - tonynet-a
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
#networks:
#  tonynet-a:
#    external:
#      name: tonynet